"""app ticket.phone

Revision ID: ad3258392c44
Revises: 43273437e9c9
Create Date: 2026-05-04 14:16:39.070357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad3258392c44'
down_revision: Union[str, Sequence[str], None] = '43273437e9c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'books', 'users', ['user_id'], ['id'])
    op.add_column('tickets', sa.Column('phone', sa.String(), nullable=True))
    op.create_foreign_key(None, 'users', 'venues', ['venue_id'], ['id'])
    op.alter_column('venues', 'admin_chat_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'admin_chat_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('tickets', 'phone')
    op.drop_constraint(None, 'books', type_='foreignkey')
    # ### end Alembic commands ###
