name: Pnx update

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 62.113.102.141
        username: root
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/pnx/docker
          git pull origin main
          docker compose down
          docker rmi pnx-web pnx-bot
          docker compose up -d